extern void PUT32(unsigned int, unsigned int);
extern void PUT16(unsigned int, unsigned int);
extern void PUT8(unsigned int, unsigned int);
extern unsigned int GET32(unsigned int);
extern void dummy(unsigned int);
extern void wakeup1(void);
extern void wakeup2(void);
extern void wakeup3(void);
extern unsigned int GETPC(void);
extern unsigned int GETCPSR(void);
extern void enable_irq(void);
